thorkelsdottir/pba-project

header.php
library/svef-partials/component-header.php
src/assets/scss/src/setup/font/text_setup.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/index.scss
src/assets/scss/src/styles/index.scss

raw header

---

library/svef-partials/component-header.php
package.json
src/assets/js/app.js
src/assets/js/partials/component-header.js
src/assets/scss/src/setup/font/text_setup.scss
src/assets/scss/src/setup/index.scss
src/assets/scss/src/setup/normalizer.scss
src/assets/scss/src/styles/header/header.scss
style.css

header btn animation and side menu enters and exists

---

library/navigation.php
library/svef-partials/component-footer.php
library/svef-partials/component-header.php
library/svef-partials/component-hero.php
library/svef/icons/linkarrow.svg.php
src/assets/js/app.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/index.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/sections/hero.scss

herosection og footermenu

---

functions.php
library/custom-posttypes.php
library/navigation.php
library/svef-partials/component-events.php
library/svef-partials/component-header.php
library/svef/custom_functions.php
page-templates/front.php
src/assets/images/icons/linkarrow.svg
src/assets/scss/src/setup/normalizer.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/header/index.scss
src/assets/scss/src/styles/header/menu.scss

menu nav kláraðru í bili

---

.gitignore
functions.php
library/navigation.php
library/svef-partials/component-events.php
library/svef-partials/component-footer.php
library/svef-partials/component-header.php
library/svef-partials/component-hero.php
library/svef-partials/component-introtext.php
library/svef-partials/component-statistics.php
library/svef/custom_functions.php
library/svef/icons/linkarrow.svg.php
page-templates/front.php
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/menu.scss
src/assets/scss/src/styles/sections/events.scss
src/assets/scss/src/styles/sections/index.scss

events secton with extensice scaling on everything

---

library/svef-partials/component-signup.php
package-lock.json
package.json
page-templates/front.php
src/assets/js/app.js
src/assets/js/partials/component-header.js
src/assets/js/partials/component-signup.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/index.scss
src/assets/scss/src/styles/header/signup.scss

signupstuff

---

library/svef-partials/component-imagegallery.php
page-templates/front.php
src/assets/js/partials/component-imagegallery.js
src/assets/scss/src/styles/sections/imagegallery.scss
src/assets/scss/src/styles/sections/index.scss

imagegallery-slider is almost ready

---

library/svef-partials/component-events.php
library/svef-partials/component-jobfeed.php
page-templates/front.php
src/assets/js/partials/component-imagegallery.js
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/sections/index.scss
src/assets/scss/src/styles/sections/jobfeed.scss

job section ready

---

library/events-custom-post-types.php
library/svef-partials/component-events.php
library/svef-partials/component-imagegallery.php
library/svef-partials/component-introtext.php
library/svef-partials/component-winners-slider.php
page-templates/page-awards.php
src/assets/js/app.js
src/assets/js/partials/component-imagegallery.js
src/assets/js/partials/component-winnersslider.js
src/assets/scss/src/globals/global-colors.scss
src/assets/scss/src/globals/index.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/globals/variables.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/sections/index.scss
src/assets/scss/src/styles/sections/winners-slider.scss

nokkrarbreitingar og slider fyrir winners á´góðri leið

---

library/svef-partials/component-boardmembers.php
src/assets/scss/src/globals/global-colors.scss
src/assets/scss/src/styles/sections/boardmembers.scss

boardmembers finished

---

library/boardmembers-custom-post-types.php

birna að setja upp members post type

---

functions.php
library/boardmembers-custom-post-types.php
library/svef-partials/component-boardmembers.php

done with boardmember cards

---

library/svef-partials/component-boardmembers.php
library/svef-partials/component-boardmembersMax.php
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/globals/variables.scss
src/assets/scss/src/styles/sections/boardmembers.scss

boardmembers ready

---

library/svef-partials/component-boardmembersMax.php
library/svef-partials/component-imagegallery.php
src/assets/js/partials/component-imagegallery.js
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/sections/boardmembers.scss
src/assets/scss/src/styles/sections/imagegallery.scss

board done

---

functions.php
library/svef-partials/component-jobfeed.php
library/svef-partials/component-winners-slider.php
library/svef/custom-scraper.php
library/svef/custom_ajax.php
library/svef/custom_functions.php
library/svef/lib/simple_html_dom.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-members.js
src/assets/js/partials/component-winnersslider.js

created a scraper to get more information from the rss feed

---

library/svef-partials/component-boardmembersMax.php
library/svef-partials/component-c2a.php
library/svef-partials/component-hero.php
library/svef-partials/component-jobfeed.php
library/svef/custom-scraper.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-members.js
src/assets/scss/src/globals/index.scss
src/assets/scss/src/globals/loader.scss
src/assets/scss/src/styles/sections/jobfeed.scss

job feed avilable and a loader is setup as well

---

library/svef/custom-scraper.php
library/svef/custom_ajax.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-header.js
src/assets/js/partials/component-imagegallery.js
src/assets/js/partials/component-members.js
src/assets/js/partials/component-winnersslider.js

commented the scraping thingy

---

library/svef-partials/component-events.php
library/svef-partials/component-hero.php
library/svef/custom-scraper.php
library/svef/custom_ajax.php
library/svef/custom_translations.php
page-templates/front.php
page-templates/page-awards.php
page-templates/page-events.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-loadmore.js
src/assets/js/partials/component-members.js
src/assets/scss/src/globals/sections.scss

Events page with load more button

---

library/svef-partials/component-hero.php
library/svef-partials/component-logowall.php
page-templates/page-iceweb.php
src/assets/scss/src/globals/global-colors.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/index.scss
src/assets/scss/src/styles/page-templates/article.scss
src/assets/scss/src/styles/page-templates/index.scss
src/assets/scss/src/styles/sections/hero.scss
src/assets/scss/src/styles/sections/logowall.scss

Icewebb sett up þarf að skoða content betur

---

library/enqueue-scripts.php
library/svef-partials/component-c2a.php
library/svef-partials/component-hero.php
library/svef/custom-scraper.php
library/svef/custom_ajax.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-signup.js
src/assets/js/partials/component-translate.js
src/assets/scss/src/globals/global-colors.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/globals/variables.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/footer/footer.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/hero.scss
src/assets/scss/src/styles/sections/index.scss
src/assets/scss/src/styles/sections/jobfeed.scss

ýmsar lagfæringar og dúll í hero og c2a, endalaust ves með back color

---

library/svef-partials/component-introtext.php
library/svef-partials/component-winners-slider.php
library/svef/custom_functions.php
library/svef/icons/cursor-winnner.svg.php
library/svef/icons/down-caret.svg
page-templates/front.php
page-templates/page-awards.php
src/assets/js/app.js
src/assets/js/partials/component-textticker.js
src/assets/js/partials/component-winnersslider.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/sections/imagegallery.scss
src/assets/scss/src/styles/sections/winners-slider.scss

ticker,winnerslider,arrowhover

---

library/svef-partials/component-boardmembers.php
library/svef-partials/component-c2a.php
library/svef-partials/component-hero.php
library/svef-partials/component-jobfeed.php
src/assets/js/app.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-jobfeed.js
src/assets/js/partials/component-loadmore.js
src/assets/js/partials/component-logowall.js
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/hero.scss
src/assets/scss/src/styles/sections/jobfeed.scss

scaling branches and fixing small stuff

---

src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/hero.scss

back color fixed for darkmode

---

src/assets/js/partials/component-logowall.js
src/assets/scss/src/styles/sections/logowall.scss

logowall completegn logo-wall-logic

---

src/assets/js/partials/component-logowall.js

logowall commented

---

footer.php
library/svef-partials/component-coockie-consent.php
library/svef/custom_translations.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-cookie-consent.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/header/menu.scss
src/assets/scss/src/styles/sections/cookie-consent.scss
src/assets/scss/src/styles/sections/index.scss

Cookie consent

---

library/svef-partials/component-header.php
library/svef-partials/component-logowall.php
library/svef/custom_functions.php
src/assets/js/partials/component-header.js
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/menu.scss

nav bar scaled and body frosen when menu is open

---

header.php
library/svef-partials/component-c2a.php
library/svef-partials/component-logowall.php
package.json
src/assets/js/app.js
src/assets/js/partials/component-header.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/hero.scss
src/assets/scss/src/styles/sections/jobfeed.scss
yarn.lock

some changes but mostlu failing to init barba

---

library/svef-partials/component-hero.php
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-statistic.js

lagað efri að síða var gerð læv

---

library/svef-partials/component-boardmembers-cards.php
library/svef-partials/component-boardmembers-page.php
page-templates/about.php
page-templates/board.php
page-templates/page-iceweb.1.php
page-templates/page-svef.php
src/assets/js/app.js
src/assets/js/global-functions.js
src/assets/js/partials/component-member-page.js
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/page-templates/article.scss

scroll to correct member and Gutenberg implemented for pages

---

header.php
library/svef-partials/component-boardmembers-page.php
library/svef-partials/component-events.php
library/svef/custom_ajax.php
library/svef/custom_functions.php
src/assets/js/partials/component-header.js
src/assets/js/partials/component-loadmore.js
src/assets/scss/src/globals/global-colors.scss
src/assets/scss/src/styles/sections/boardmembers.scss
src/assets/scss/src/styles/sections/events.scss
src/assets/scss/src/styles/sections/hero.scss

fixes to passed events

---

library/svef-partials/component-c2a.php
library/svef/icons/maskTwoSqrs.svg.php
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-set-carousel-by-class.js
src/assets/scss/src/styles/sections/c2a.scss

more ifxes

---

library/svef-partials/component-header.php
library/svef-partials/component-signup.php
src/assets/js/partials/component-header.js
src/assets/js/partials/component-signup.js
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/menu.scss
src/assets/scss/src/styles/header/signup.scss

formbuttonscale

---

library/svef-partials/component-c2a.php
library/svef-partials/component-hero.php
library/svef-partials/component-introtext.php
library/svef-partials/component-jobfeed.php
src/assets/js/app.js
src/assets/js/partials/component-appear.js
src/assets/js/partials/component-set-carousel-by-class.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/setup/normalizer.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/events.scss

C2a agina and agin

---

library/svef-partials/component-c2a.php
library/svef-partials/component-footer.php
library/svef/icons/maskTwoSqrs.svg.php
src/assets/js/partials/component-appear.js
src/assets/js/window-load.js
src/assets/scss/src/styles/sections/c2a.scss

ok now we are there with the fucking c2a :)

---

src/assets/js/partials/component-statistic.js

strangs extra characters in component-statistics.js

---

library/svef-partials/component-boardmembers-cards.php
library/svef-partials/component-boardmembers-page.php
library/svef-partials/component-c2a.php
library/svef-partials/component-events.php
library/svef-partials/component-hero.php
library/svef-partials/component-introtext.php
library/svef-partials/component-logowall.php
library/svef/icons/maskTwoSqrs.svg.php
src/assets/images/maskTwoSqrs.svg
src/assets/js/partials/component-statistic.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/footer/footer.scss
src/assets/scss/src/styles/sections/boardmembers.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/events.scss
src/assets/scss/src/styles/sections/imagegallery.scss
src/assets/scss/src/styles/sections/jobfeed.scss
src/assets/scss/src/styles/sections/logowall.scss
src/assets/scss/src/styles/sections/statistics.scss

morescalingready

---

.gitignore
library/svef-partials/component-logowall.php
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-statistic.js

some small changes

---

library/svef-partials/component-c2a.php
library/svef-partials/component-header.php
library/svef-partials/component-hero.php
library/svef-partials/component-jobfeed.php
src/assets/js/partials/component-appear.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/window-load.js
src/assets/scss/src/globals/loader.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/header/window-loader.scss
src/assets/scss/src/styles/sections/c2a.scss

C2a mask paralax

---

library/svef-partials/component-footer.php
library/svef-partials/component-signup.php

ajax forms activated

---

library/svef-partials/component-signup.php

acf for signip info text

---

src/assets/js/global-functions.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-winnersslider.js

dots are indexed

---

src/assets/js/partials/component-header.js
src/assets/js/partials/component-winnersslider.js
src/assets/js/scrollmagic-functions.js
src/assets/js/window-load.js
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/c2a.scss

added function that decects browser and unpluggs svg mask for safari

---

library/svef-custom-functions/custom_ajax.php
library/svef-partials/component-news-items.php
src/assets/js/global-functions.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-loadmore.js
src/assets/js/scrollmagic-functions.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/global-colors.scss
src/assets/scss/src/globals/variables.scss
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/footer/footer.scss
src/assets/scss/src/styles/sections/c2a.scss

added news read more and fixed how they load

---

src/assets/js/scrollmagic-functions.js

fixed load animation

---

library/svef-partials/component-hero.php
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-loadmore.js
src/assets/js/scrollmagic-functions.js
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/hero.scss

fixed small nuanced in heroe in mobile sizes

---

src/assets/scss/src/styles/header/signup.scss

scrool smoooooooooothhhh

---

src/assets/js/scrollmagic-functions.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss

small backtracks

---

library/svef-custom-functions/custom_functions.php
src/assets/js/global-functions.js
src/assets/js/partials/component-header.js
src/assets/scss/src/styles/header/signup.scss

fixed arialabel in lang menu with javascrip

---

src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/boardmembers.scss
src/assets/scss/src/styles/sections/jobfeed.scss

littlefixex-jobfeed-boardmembers-stuff

---

library/svef-partials/component-logowall.php
library/svef-partials/component-video.php
library/svef-partials/component-winners-slider.php
page-templates/page-awards.php
src/assets/js/global-functions.js
src/assets/scss/app.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/header/signup.scss

video section

---

library/svef-partials/component-hero.php

fixed link text title not apearing when filled in

---

functions.php
library/svef-custom-functions/custom_translations.php
library/svef-partials/component-c2a.php
library/svef-partials/component-header.php
library/svef-partials/component-hero.php

more fix for links on c2a and hero

---

library/svef-partials/component-events.php

fix events links

---

library/svef-custom-functions/custom_translations.php
library/svef-partials/component-boardmembers-page.php
library/svef-partials/component-hero.php
library/svef-partials/component-imagegallery.php
style.css

fix mobile img size

---

library/svef-partials/component-boardmembers-cards.php
library/svef-partials/component-boardmembers-page.php
library/svef-partials/component-c2a.php
library/svef-partials/component-hero.php
library/svef-partials/component-imagegallery.php
library/svef-partials/component-jobfeed.php
library/svef-partials/component-news-items.php
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-imagegallery.js
src/assets/scss/src/styles/sections/c2a.scss

stop carousel autoplay while interaction /dragging the charousel

---

library/svef-partials/component-boardmembers-cards.php
library/svef-partials/component-c2a.php
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/c2a.scss

some fixes

---

library/svef-custom-functions/custom_ajax.php
library/svef-partials/component-boardmembers-cards.php
src/assets/js/partials/component-winnersslider.js

fix- img retina and news excerpt

---

library/svef-partials/component-boardmembers-cards.php
src/assets/scss/src/styles/header/signup.scss
style.css

fix member card path

---

library/svef-partials/component-boardmembers-page.php
library/svef-partials/component-c2a.php
page-templates/board.php

remove intro text from stjorn page

---

library/svef-partials/component-hero.php
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/menu.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/boardmembers.scss
src/assets/scss/src/styles/sections/hero.scss

cardfixes and more

---

src/assets/scss/src/styles/sections/hero.scss

fixed owl dots

---

header.php

analitics code

---

page-templates/page-common.php
page-templates/page-news.php
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/page-templates/article.scss
src/assets/scss/src/styles/sections/events.scss
src/assets/scss/src/styles/sections/news.scss

margintext changes

---

library/enqueue-scripts.php
library/svef-custom-functions/custom_functions.php
src/assets/js/global-functions.js
src/assets/js/partials/component-header.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/partials/component-imagegallery.js
src/assets/js/partials/component-winnersslider.js
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss

set dots to aria hidden

---

library/svef-partials/component-signup.php
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/header/header.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/statistics.scss

accessablefix

---

src/assets/scss/src/setup/typography.scss

one font thing

---

library/svef-custom-functions/custom-scraper.php
library/svef-partials/component-header.php
library/svef-partials/component-hero.php
library/svef-partials/component-signup.php
src/assets/scss/src/globals/sections.scss

fix  stray div tags and aria lables

---

library/svef-partials/component-hero.php
page-templates/page-common.php
page-templates/page-iceweb.php
page-templates/page-news.php
single-events.php
single.php
src/assets/scss/src/setup/typography.scss
src/assets/scss/src/styles/page-templates/article.scss
src/assets/scss/src/styles/sections/c2a.scss
src/assets/scss/src/styles/sections/events.scss
src/assets/scss/src/styles/sections/news.scss

some margin stuff

---

library/svef-partials/component-c2a.php
library/svef-partials/component-introtext.php
single-events.php

added c2a-2nd to events landing pages

---

library/svef-partials/component-hero.php
src/assets/js/window-load.js

start loader on anchor click so we get the loader instantly

---

library/svef-partials/component-hero.php

fixed if statement for herobanner link

---

library/svef-partials/component-footer.php
src/assets/js/app.js
src/assets/js/dictionary.js
src/assets/js/partials/component-header.js
src/assets/js/partials/component-hero-slider.js
src/assets/js/window-load.js
src/assets/scss/src/globals/loader.scss

Backtrack load

---

library/svef-custom-functions/custom_translations.php
library/svef-partials/component-footer.php
library/svef-partials/component-logowall.php
library/svef-partials/component-signup.php
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/globals/variables.scss
src/assets/scss/src/styles/footer/footer.scss
src/assets/scss/src/styles/header/signup.scss
src/assets/scss/src/styles/sections/winners-slider.scss

language assitions

---

library/svef-partials/component-winners-slider.php

fixed winnersslider

---

library/svef-partials/component-boardmembers-cards.php
library/svef-partials/component-boardmembers-page.php
library/svef-partials/component-hero.php
single-events.php
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/globals/sections.scss
src/assets/scss/src/styles/sections/boardmembers.scss
src/assets/scss/src/styles/sections/events.scss
src/assets/scss/src/styles/sections/hero.scss

morerestfixing

---

header.php
library/svef-custom-functions/custom_ajax.php
src/assets/js/partials/component-header.js

wp engine not accepting session form darkmode so changed to cookie

---

header.php

burtmedanalytics

---

library/svef-partials/component-logowall.php
src/assets/scss/src/globals/global-classes.scss
src/assets/scss/src/styles/sections/logowall.scss

fixed logo wall to accept less icons thaa 6 and not go nuts

---

header.php
library/svef-custom-functions/custom_ajax.php
src/assets/js/partials/component-header.js

fiexed header.php from session to cookie

---

src/assets/js/partials/component-header.js

js backup plan

---

header.php
library/svef-custom-functions/custom_ajax.php
src/assets/js/partials/component-header.js

this is to have smooth darkmode on load"

---

header.php

cleaned out seo meta tags because client will use Yoast plugin

---

library/svef-partials/component-winners-slider.php
src/assets/js/partials/component-header.js
src/assets/js/partials/component-jobfeed.js
src/assets/js/partials/component-winnersslider.js
src/assets/scss/src/styles/sections/c2a.scss

fixed blur back img

---

header.php
library/enqueue-scripts.php
library/svef-custom-functions/custom_functions.php
src/assets/js/partials/component-header.js
src/assets/scss/app.scss

allnokkrar breiting t.d. hvernig darkmode er settup í vefkökur
